import React,{useState}from'react';import{api}from'../api';import{BedDouble,ReceiptText,ShieldCheck,ConciergeBell,UtensilsCrossed,Flower2,Car,CreditCard,CheckCircle2,LogOut,KeyRound,ClipboardCheck,DoorOpen}from'lucide-react';
const money=n=>`₹${Number(n||0).toLocaleString('en-IN')}`;
export default function GuestPortal(){
 const[credentials,setCredentials]=useState({confirmationNumber:'',phone:''}),[data,setData]=useState(null),[request,setRequest]=useState({category:'Housekeeping',description:''}),[msg,setMsg]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[pre,setPre]=useState({nationality:'India',idType:'Aadhaar',idNumber:'',signatureName:'',registrationAccepted:false,identityVerified:false}),[food,setFood]=useState({name:'Club Sandwich',qty:1,price:450}),[spa,setSpa]=useState({service:'Signature Massage',startAt:''});
 async function lookup(){setError('');setLoading(true);try{const r=await api.post('/public/guest/lookup',credentials);setData(r.data)}catch(e){setError(e.response?.data?.message||e.message)}finally{setLoading(false)}}
 async function service(category=request.category,description=request.description){setError('');if(!description)return setError('Tell us what you need.');try{const r=await api.post('/public/guest/service-request',{...credentials,category,description});setMsg(`Request created: ${r.data.reference}`);setRequest({...request,description:''})}catch(e){setError(e.response?.data?.message||e.message)}}
 const calc=f=>f?(f.items||[]).reduce((s,i)=>s+(i.amount||0)+(i.tax||0)-(i.discount||0),0)-(f.payments||[]).reduce((s,p)=>s+(p.amount||0)-(p.refundedAmount||0),0):0;
 async function payBalance(){const amount=calc(data.folio);if(!(amount>0))return;setLoading(true);setError('');try{const propertyCode=data.reservation.property?.code||import.meta.env.VITE_DEFAULT_PROPERTY_CODE||'HTL001';const{data:order}=await api.post('/public/payments/create-order',{propertyCode,amount,currency:'INR',receipt:data.reservation.confirmationNumber});if(order.provider==='mock'){await api.post('/public/payments/capture',{...credentials,orderId:order.orderId,paymentId:`pay_mock_${Date.now()}`,signature:'mock_signature',amount,currency:'INR',method:'Online'});await lookup();setMsg('Payment captured successfully.')}else setError('Secure provider checkout is enabled; complete payment from booking checkout.')}catch(e){setError(e.response?.data?.message||e.message)}finally{setLoading(false)}}
 async function preCheckin(){try{await api.post('/public/guest/pre-checkin',{...credentials,guest:{nationality:pre.nationality,idType:pre.idType,idNumber:pre.idNumber},signatureName:pre.signatureName,registrationAccepted:pre.registrationAccepted,identityVerified:pre.identityVerified});setMsg('Pre-arrival check-in information submitted.');await lookup()}catch(e){setError(e.response?.data?.message||e.message)}}
 async function digitalKey(){try{const r=await api.post('/public/guest/digital-key',credentials);setMsg(r.data?.keyCode?`Digital key: ${r.data.keyCode}`:'Digital key not active yet.')}catch(e){setError(e.response?.data?.message||e.message)}}
 async function checkout(){try{const r=await api.post('/public/guest/checkout-request',credentials);setMsg(`Digital checkout requested: ${r.data.reference}`)}catch(e){setError(e.response?.data?.message||e.message)}}
 async function orderFood(){try{const r=await api.post('/public/guest/food-order',{...credentials,items:[food]});setMsg(`Room service order created: ${r.data.order._id}`)}catch(e){setError(e.response?.data?.message||e.message)}}
 async function bookSpa(){try{const r=await api.post('/public/guest/spa-book',{...credentials,service:spa.service,startAt:spa.startAt});setMsg(`Spa booking created: ${r.data._id}`)}catch(e){setError(e.response?.data?.message||e.message)}}
 return <div className="publicPage guestPortalPage"><header className="publicNav"><div className="publicBrand"><div className="brandMark">H</div><div><b>Guest Portal</b><span>Digital Stay Journey</span></div></div><nav><a href="/book">Book a room</a>{data&&<button onClick={()=>setData(null)}><LogOut size={15}/> Sign out</button>}</nav></header>
 {!data?<main className="guestLoginWrap"><div className="guestLoginStory"><span className="eyebrow">SELF-SERVICE GUEST JOURNEY</span><h1>Your stay, in one place.</h1><p>Reservation, pre-check-in, digital key, services, folio, payment and checkout requests.</p></div><div className="publicCard guestLoginCard"><h2>Access my stay</h2><input placeholder="Confirmation number" value={credentials.confirmationNumber} onChange={e=>setCredentials({...credentials,confirmationNumber:e.target.value})}/><input placeholder="Registered phone" value={credentials.phone} onChange={e=>setCredentials({...credentials,phone:e.target.value})}/><button className="goldButton" onClick={lookup} disabled={loading}>{loading?'Checking…':'Open My Stay'}</button>{error&&<p className="error">{error}</p>}</div></main>:
 <main className="guestDashboard"><section className="guestWelcome"><div><span className="eyebrow">WELCOME BACK</span><h1>{data.reservation.guest?.fullName}</h1><p>{data.reservation.confirmationNumber} · {data.reservation.roomType?.name}</p></div><span className="statusBig">{data.reservation.status}</span></section>
 <div className="guestStats"><div className="publicCard"><BedDouble/><span>Room</span><b>{data.reservation.room?.number||'To be assigned'}</b><small>{data.reservation.roomType?.name}</small></div><div className="publicCard"><ReceiptText/><span>Folio balance</span><b>{money(calc(data.folio))}</b><small>{data.folio?.items?.length||0} posted charges</small></div><div className="publicCard"><ShieldCheck/><span>Stay</span><b>{new Date(data.reservation.checkIn).toLocaleDateString()}</b><small>to {new Date(data.reservation.checkOut).toLocaleDateString()}</small></div></div>
 <section className="guestServiceGrid"><button onClick={()=>service('Housekeeping','Please service my room')}><ConciergeBell/><b>Housekeeping</b><span>Cleaning & amenities</span></button><button onClick={digitalKey}><KeyRound/><b>Digital Key</b><span>Access key after check-in</span></button><button onClick={checkout}><DoorOpen/><b>Checkout</b><span>Request digital checkout</span></button><button onClick={()=>service('Transport','Please arrange airport / local transport')}><Car/><b>Transport</b><span>Airport & local rides</span></button></section>
 <div className="grid2"><div className="publicCard"><h2><ClipboardCheck size={18}/> Pre-arrival check-in</h2><div className="formGrid"><input placeholder="Nationality" value={pre.nationality} onChange={e=>setPre({...pre,nationality:e.target.value})}/><select value={pre.idType} onChange={e=>setPre({...pre,idType:e.target.value})}><option>Aadhaar</option><option>Passport</option><option>Driving Licence</option></select><input placeholder="ID / Passport number" value={pre.idNumber} onChange={e=>setPre({...pre,idNumber:e.target.value})}/><input placeholder="Signature name" value={pre.signatureName} onChange={e=>setPre({...pre,signatureName:e.target.value})}/><label className="inline"><input type="checkbox" checked={pre.identityVerified} onChange={e=>setPre({...pre,identityVerified:e.target.checked})}/>Identity confirmed</label><label className="inline"><input type="checkbox" checked={pre.registrationAccepted} onChange={e=>setPre({...pre,registrationAccepted:e.target.checked})}/>Accept registration form</label><button className="goldButton" onClick={preCheckin}>Submit pre-check-in</button></div></div>
 <div className="publicCard"><h2>Folio & payment</h2>{(data.folio?.items||[]).slice(-8).map(i=><div className="summaryLine" key={i._id}><span>{i.description}</span><b>{money((i.amount||0)+(i.tax||0)-(i.discount||0))}</b></div>)}<div className="summaryTotal"><span>Balance</span><b>{money(calc(data.folio))}</b></div><button className="goldButton" disabled={!(calc(data.folio)>0)||loading} onClick={payBalance}><CreditCard size={16}/> {loading?'Processing…':'Pay Balance'}</button></div></div>
 <div className="grid2"><div className="publicCard"><h2><UtensilsCrossed size={18}/> Room Service</h2><div className="formGrid"><input value={food.name} onChange={e=>setFood({...food,name:e.target.value})}/><input type="number" value={food.qty} onChange={e=>setFood({...food,qty:Number(e.target.value)})}/><input type="number" value={food.price} onChange={e=>setFood({...food,price:Number(e.target.value)})}/><button onClick={orderFood}>Place room-service order</button></div></div><div className="publicCard"><h2><Flower2 size={18}/> Spa & Wellness</h2><div className="formGrid"><input value={spa.service} onChange={e=>setSpa({...spa,service:e.target.value})}/><input type="datetime-local" value={spa.startAt} onChange={e=>setSpa({...spa,startAt:e.target.value})}/><button onClick={bookSpa}>Book spa</button></div></div></div>
 <div className="publicCard"><h2>Request a service</h2><div className="formGrid"><select value={request.category} onChange={e=>setRequest({...request,category:e.target.value})}><option>Housekeeping</option><option>Restaurant</option><option>Spa</option><option>Transport</option><option>Maintenance</option><option>General</option></select><input placeholder="What do you need?" value={request.description} onChange={e=>setRequest({...request,description:e.target.value})}/><button className="goldButton" onClick={()=>service()}>Send Request</button></div>{msg&&<div className="notice"><CheckCircle2 size={16}/> {msg}</div>}{error&&<p className="error">{error}</p>}</div>
 </main>}</div>
}
