import React,{useEffect,useMemo,useState}from'react';
import{useParams}from'react-router-dom';
import{useMutation,useQuery,useQueryClient}from'@tanstack/react-query';
import{api}from'../api';
import{Page,Empty}from'../components';import{useAuth}from'../AuthContext';

const cfg={
 'laundry-orders':{title:'Laundry Production',subtitle:'Guest laundry, hotel linen production and folio posting',stages:['Received','Washing','Drying','Ironing','Ready','Delivered'],actions:[['Washing','/operations/laundry/:id/status',{status:'Washing'}],['Ready','/operations/laundry/:id/status',{status:'Ready'}],['Deliver + Post','/operations/laundry/:id/status',{status:'Delivered'}]]},
 'linen-items':{title:'Linen Control',subtitle:'Clean, in-room, laundry, damaged, missing and par-stock visibility'},
 'minibar-entries':{title:'Minibar Control',subtitle:'Capture consumption, deduct stock and post charges to guest folio',actions:[['Post to Folio','/operations/minibar/:id/post',{}]]},
 'spa-appointments':{title:'Spa & Wellness',subtitle:'Appointments, service lifecycle and room/folio charging',stages:['Booked','Confirmed','In Progress','Completed'],actions:[['Confirm','/operations/spa/:id/status',{status:'Confirmed'}],['Start','/operations/spa/:id/status',{status:'In Progress'}],['Complete + Post','/operations/spa/:id/status',{status:'Completed'}]]},
 'events':{title:'Banquet & Events',subtitle:'Function calendar, BEO control and event execution',stages:['Inquiry','Tentative','Confirmed','BEO Issued','In Progress','Completed'],actions:[['Confirm','/operations/event/:id/status',{status:'Confirmed'}],['Issue BEO','/operations/event/:id/status',{status:'BEO Issued'}],['Complete','/operations/event/:id/status',{status:'Completed'}]]},
 'inventory-items':{title:'Inventory Control',subtitle:'Department stock, reorder visibility, stock adjustments and audit trail',actions:[['Add 1 Stock','/operations/inventory/:id/adjust',{qty:1,type:'adjustment'}],['Consume 1','/operations/inventory/:id/adjust',{qty:-1,type:'consumption'}]]},
 'maintenance-work-orders':{title:'Engineering Work Orders',subtitle:'Corrective maintenance, room blocking and verification',stages:['Open','Assigned','In Progress','On Hold','Completed','Verified'],actions:[['Start','/operations/maintenance/:id/status',{status:'In Progress'}],['Complete','/operations/maintenance/:id/status',{status:'Completed'}],['Verify','/operations/maintenance/:id/status',{status:'Verified'}]]},
 'preventive-maintenance':{title:'Preventive Maintenance',subtitle:'Recurring service plans and work-order generation',actions:[['Generate Work Order','/operations/preventive/:id/generate-work-order',{}]]},
 'assets':{title:'Asset Register',subtitle:'Lifecycle, warranty, location and maintenance history'},
 'transport-requests':{title:'Guest Transportation',subtitle:'Airport transfer, chauffeur and dispatch management',stages:['Requested','Assigned','Dispatched','Picked Up','Completed'],actions:[['Assign','/operations/transport/:id/status',{status:'Assigned'}],['Dispatch','/operations/transport/:id/status',{status:'Dispatched'}],['Complete + Post','/operations/transport/:id/status',{status:'Completed'}]]},
 'lost-found':{title:'Lost & Found',subtitle:'Custody, guest contact, return and disposal tracking',stages:['Found','Stored','Guest Contacted','Returned','Disposed'],actions:[['Store','/operations/lost-found/:id/status',{status:'Stored'}],['Guest Contacted','/operations/lost-found/:id/status',{status:'Guest Contacted'}],['Returned','/operations/lost-found/:id/status',{status:'Returned'}]]},
 'incidents':{title:'Security Incidents',subtitle:'Restricted incident logging, investigation and resolution',stages:['Open','Investigating','Action Required','Resolved','Closed'],actions:[['Investigating','/operations/incident/:id/status',{status:'Investigating'}]]},
 'shifts':{title:'Shift Management',subtitle:'Department rosters, shift changes and approvals',actions:[['Approve','/operations/shift/:id/approve',{}]]},
 'attendance':{title:'Attendance',subtitle:'Employee attendance records and payroll handoff readiness'},
 'cashier-shifts':{title:'Cashier Control',subtitle:'Opening balance, receipts, paid-outs, closing and variance review',actions:[['Close Shift','/operations/cashier/:id/close',{actualCash:0}]]},
 'integrations':{title:'Integration Hub',subtitle:'Provider configuration, adapter validation, logs and retry readiness',actions:[['Test Adapter','/operations/integration/:id/test',{}]]},
};
const nice=s=>String(s||'').replace(/([A-Z])/g,' $1').replace(/^./,x=>x.toUpperCase());
const toInput=(v,t)=>{if(v==null)return'';if(t==='Date'){const d=new Date(v);if(Number.isNaN(d.getTime()))return'';return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}if(t==='Mixed')return typeof v==='string'?v:JSON.stringify(v);return v};
const parse=(v,t)=>{if(t==='Number')return v===''?undefined:Number(v);if(t==='Boolean')return!!v;if(t==='Date')return v?new Date(v).toISOString():undefined;if(t==='Mixed'){if(v==='')return undefined;try{return JSON.parse(v)}catch{return v}}return v};
export default function OperationsCenter(){
 const{module}=useParams(),qc=useQueryClient(),{can}=useAuth(),ui=cfg[module]||{title:nice(module),subtitle:'Enterprise operations workflow'};
 const{data:meta={}}=useQuery({queryKey:['module-meta'],queryFn:()=>api.get('/modules/meta').then(r=>r.data)});const def=meta[module];
 const{data:rows=[],isLoading,error}=useQuery({queryKey:['module',module],enabled:!!def,queryFn:()=>api.get(`/modules/${module}`).then(r=>r.data)});
 const fields=useMemo(()=>def?Object.keys(def.fields):[],[def]);const canCreate=can(`modules.${module}.create`),canUpdate=can(`modules.${module}.update`),canDelete=can(`modules.${module}.delete`);const[form,setForm]=useState({});const[editing,setEditing]=useState(null);const[msg,setMsg]=useState('');
 useEffect(()=>{setForm({});setEditing(null);setMsg('')},[module]);const refresh=()=>qc.invalidateQueries({queryKey:['module',module]});
 const save=useMutation({mutationFn:({id,data})=>id?api.patch(`/modules/${module}/${id}`,data):api.post(`/modules/${module}`,data),onSuccess:()=>{refresh();setForm({});setEditing(null);setMsg('Saved successfully')},onError:e=>setMsg(e.response?.data?.message||e.message)});
 const action=useMutation({mutationFn:({url,body})=>api.post(url,body),onSuccess:()=>{refresh();setMsg('Workflow action completed')},onError:e=>setMsg(e.response?.data?.message||e.message)});
 const remove=useMutation({mutationFn:id=>api.delete(`/modules/${module}/${id}`),onSuccess:()=>{refresh();setMsg('Deleted successfully')},onError:e=>setMsg(e.response?.data?.message||e.message)});
 if(!def)return <Page title="Module not found" subtitle="No module definition"><Empty/></Page>;
 const submit=()=>{const data={};fields.forEach(f=>{const v=parse(form[f],def.fields[f]);if(v!==undefined)data[f]=v});save.mutate({id:editing?._id,data})};
 const edit=r=>{const f={};fields.forEach(k=>f[k]=toInput(r[k],def.fields[k]));setForm(f);setEditing(r);window.scrollTo({top:0,behavior:'smooth'})};
 return <Page title={ui.title} subtitle={ui.subtitle}>
  {ui.stages&&<div className="workflowStrip">{ui.stages.map((s,i)=><div className="workflowStage" key={s}><span>{i+1}</span><b>{s}</b></div>)}</div>}
  <div className="metricGrid"><div className="metric"><span>Total records</span><b>{rows.length}</b></div><div className="metric"><span>Workflow</span><b>{ui.actions?.length?'Active':'Configured'}</b></div><div className="metric"><span>Property scoped</span><b>Yes</b></div><div className="metric"><span>Audit ready</span><b>Yes</b></div></div>
  {(canCreate||editing)&&<div className="card"><div className="sectionHead"><div><h3>{editing?'Edit operational record':'New operational record'}</h3><p className="muted">Property-scoped data with role permissions and workflow actions.</p></div>{editing&&<button className="ghost" onClick={()=>{setEditing(null);setForm({})}}>Cancel</button>}</div>{msg&&<div className="notice">{msg}</div>}
   <div className="formGrid">{fields.map(f=>{const t=def.fields[f],v=form[f]??'';if(t==='Boolean')return <label className="inline" key={f}><input type="checkbox" checked={!!form[f]} onChange={e=>setForm({...form,[f]:e.target.checked})}/>{nice(f)}</label>;if(t==='Date')return <label key={f}>{nice(f)}<input type="datetime-local" value={v} onChange={e=>setForm({...form,[f]:e.target.value})}/></label>;if(t==='Mixed')return <label key={f}>{nice(f)}<textarea rows="3" value={v} onChange={e=>setForm({...form,[f]:e.target.value})}/></label>;return <label key={f}>{nice(f)}<input type={t==='Number'?'number':'text'} value={v} onChange={e=>setForm({...form,[f]:e.target.value})}/></label>})}<div className="actions">{(editing?canUpdate:canCreate)&&<button className="primary" onClick={submit} disabled={save.isPending}>{editing?'Update':'Save'}</button>}</div></div>
  </div>}
  <div className="tableWrap"><table><thead><tr>{fields.slice(0,7).map(f=><th key={f}>{nice(f)}</th>)}<th>Workflow actions</th></tr></thead><tbody>{rows.map(r=><tr key={r._id}>{fields.slice(0,7).map(f=><td key={f}>{typeof r[f]==='object'&&r[f]!==null?JSON.stringify(r[f]).slice(0,90):String(r[f]??'—')}</td>)}<td><div className="rowActions">{canUpdate&&<button className="ghost" onClick={()=>edit(r)}>Edit</button>}{canUpdate&&(ui.actions||[]).map(([label,path,body])=><button className="ghost" key={label} disabled={action.isPending} onClick={()=>action.mutate({url:path.replace(':id',r._id),body})}>{label}</button>)}{canDelete&&<button className="danger" onClick={()=>confirm('Delete this record?')&&remove.mutate(r._id)}>Delete</button>}</div></td></tr>)}</tbody></table>{isLoading&&<div className="pad">Loading…</div>}{error&&<div className="pad error">{error.response?.data?.message||error.message}</div>}{!isLoading&&!rows.length&&<Empty/>}</div>
 </Page>
}
