const router=require('express').Router();
const asyncHandler=require('../utils/asyncHandler');
const auth=require('../middleware/auth');
const tenant=require('../middleware/tenant');
const permit=require('../middleware/permit');
const {Reservation,Guest,Room,Folio,HousekeepingTask}=require('../models/core');
const audit=require('../utils/audit');
const {v4:uuid}=require('uuid');
router.use(auth,tenant);
const activeStatuses={$nin:['cancelled','no-show','checked-out']};
const overlap=(qIn,qOut)=>({checkIn:{$lt:qOut},checkOut:{$gt:qIn},status:activeStatuses});
const days=(a,b)=>Math.max(1,Math.ceil((new Date(b)-new Date(a))/86400000));
const scope=(req,extra={})=>({...req.organizationFilter,...(req.propertyId?{property:req.propertyId}:{}),...extra});
async function ensureAvailable({organization,property,room,checkIn,checkOut,exclude}){
 if(!room)return;
 const clash=await Reservation.findOne({...(organization?{organization}:{}),property,room,_id:{$ne:exclude},...overlap(new Date(checkIn),new Date(checkOut))});
 if(clash){const e=new Error('Room conflict detected');e.status=409;throw e;}
}
async function roomStatus(req,room,status,property){
 if(!room)return;
 const q={_id:room,...req.organizationFilter,...(property?{property}:{})};
 await Room.findOneAndUpdate(q,{status});
}
async function getReservation(req,id,populate=''){
 let q=Reservation.findOne(scope(req,{_id:id}));
 if(populate)q=q.populate(populate);
 return q;
}

router.get('/',permit('reservations.view'),asyncHandler(async(req,res)=>{
 const q=scope(req);if(req.query.status)q.status=req.query.status;
 if(req.query.from||req.query.to){q.checkIn={};if(req.query.from)q.checkIn.$gte=new Date(req.query.from);if(req.query.to)q.checkIn.$lte=new Date(req.query.to)}
 res.json(await Reservation.find(q).populate('guest room roomType').sort({checkIn:1}));
}));
router.get('/availability',permit('reservations.view'),asyncHandler(async(req,res)=>{
 const checkIn=new Date(req.query.checkIn),checkOut=new Date(req.query.checkOut);if(!(checkIn<checkOut))return res.status(400).json({message:'Valid check-in/check-out required'});
 if(!req.propertyId)return res.status(400).json({message:'Property context required'});
 const occupied=await Reservation.find(scope(req,{...overlap(checkIn,checkOut),...(req.query.roomType?{roomType:req.query.roomType}:{})})).distinct('room');
 const rooms=await Room.find(scope(req,{_id:{$nin:occupied},status:{$nin:['Out of Order','Out of Service','Maintenance','Blocked']},...(req.query.roomType?{roomType:req.query.roomType}:{})})).populate('roomType');res.json(rooms);
}));
router.get('/calendar',permit('reservations.view'),asyncHandler(async(req,res)=>{
 if(!req.propertyId)return res.status(400).json({message:'Property context required'});
 const from=new Date(req.query.from||Date.now()),to=new Date(req.query.to||new Date(Date.now()+14*86400000));
 const [rooms,reservations]=await Promise.all([Room.find(scope(req)).populate('roomType').sort('number'),Reservation.find(scope(req,{checkIn:{$lt:to},checkOut:{$gt:from},status:{$nin:['cancelled']}})).populate('guest room roomType')]);
 res.json({from,to,rooms,reservations});
}));
router.get('/:id',permit('reservations.view'),asyncHandler(async(req,res)=>{const r=await getReservation(req,req.params.id,'guest room roomType');if(!r)return res.status(404).json({message:'Reservation not found'});const folio=await Folio.findOne(scope(req,{reservation:r._id}));res.json({reservation:r,folio});}));
router.post('/',permit('reservations.create'),asyncHandler(async(req,res)=>{
 if(!req.propertyId)return res.status(400).json({message:'Property context required'});
 let guest=req.body.guestId?await Guest.findOne(scope(req,{_id:req.body.guestId})):null;
 if(req.body.guestId&&!guest)return res.status(404).json({message:'Guest not found in current property/organization'});
 if(!guest)guest=await Guest.create({...req.body.guest,fullName:req.body.guest?.fullName||`${req.body.guest?.firstName||''} ${req.body.guest?.lastName||''}`.trim(),organization:req.user.organization,property:req.propertyId});
 const checkIn=new Date(req.body.checkIn),checkOut=new Date(req.body.checkOut);if(!(checkIn<checkOut))return res.status(400).json({message:'Check-out must be after check-in'});
 await ensureAvailable({organization:req.user.role==='saas_super_admin'?undefined:req.user.organization,property:req.propertyId,room:req.body.room,checkIn,checkOut});
 const reservation=await Reservation.create({...req.body,organization:req.user.organization,property:req.propertyId,guest:guest._id,nights:days(checkIn,checkOut),confirmationNumber:`${process.env.BOOKING_PREFIX||'HMS'}-${new Date().getFullYear()}-${uuid().slice(0,8).toUpperCase()}`});
 await roomStatus(req,reservation.room,'Reserved',req.propertyId);await Folio.create({organization:req.user.organization,property:req.propertyId,reservation:reservation._id,guest:guest._id,currency:process.env.DEFAULT_CURRENCY||'INR'});
 await audit(req,{action:'CREATE',module:'reservations',entityType:'Reservation',entityId:reservation._id,newValue:reservation});res.status(201).json(await reservation.populate('guest room roomType'));
}));
router.patch('/:id',permit('reservations.update'),asyncHandler(async(req,res)=>{
 const old=await getReservation(req,req.params.id);if(!old)return res.status(404).json({message:'Reservation not found'});
 const cin=req.body.checkIn||old.checkIn,cout=req.body.checkOut||old.checkOut,room=req.body.room===null?null:(req.body.room||old.room);if(!(new Date(cin)<new Date(cout)))return res.status(400).json({message:'Check-out must be after check-in'});
 await ensureAvailable({organization:old.organization,property:old.property,room,checkIn:cin,checkOut:cout,exclude:old._id});
 if(String(old.room||'')!==String(room||'')){await roomStatus(req,old.room,'Vacant Clean',old.property);await roomStatus(req,room,'Reserved',old.property)}
 const payload={...req.body,room,nights:days(cin,cout)};delete payload.organization;delete payload.property;delete payload.guest;
 const r=await Reservation.findOneAndUpdate(scope(req,{_id:req.params.id}),payload,{new:true,runValidators:true});await audit(req,{action:'UPDATE',module:'reservations',entityType:'Reservation',entityId:r._id,oldValue:old,newValue:r,reason:req.body.reason});res.json(await r.populate('guest room roomType'));
}));
router.post('/:id/assign-room',permit('reservations.update'),asyncHandler(async(req,res)=>{const r=await getReservation(req,req.params.id);if(!r)return res.status(404).json({message:'Not found'});await ensureAvailable({organization:r.organization,property:r.property,room:req.body.room,checkIn:r.checkIn,checkOut:r.checkOut,exclude:r._id});await roomStatus(req,r.room,'Vacant Clean',r.property);r.room=req.body.room||null;await r.save();await roomStatus(req,r.room,'Reserved',r.property);await audit(req,{action:'ASSIGN_ROOM',module:'reservations',entityType:'Reservation',entityId:r._id,newValue:{room:r.room}});res.json(await r.populate('guest room roomType'));}));
router.post('/:id/move-room',permit('reservations.update'),asyncHandler(async(req,res)=>{const r=await getReservation(req,req.params.id);if(!r)return res.status(404).json({message:'Not found'});await ensureAvailable({organization:r.organization,property:r.property,room:req.body.room,checkIn:r.checkIn,checkOut:r.checkOut,exclude:r._id});const oldRoom=r.room;await roomStatus(req,oldRoom,r.status==='in-house'?'Vacant Dirty':'Vacant Clean',r.property);r.room=req.body.room;await r.save();await roomStatus(req,r.room,r.status==='in-house'?'Occupied Clean':'Reserved',r.property);await audit(req,{action:'ROOM_MOVE',module:'reservations',entityType:'Reservation',entityId:r._id,oldValue:{room:oldRoom},newValue:{room:r.room},reason:req.body.reason});res.json(await r.populate('guest room roomType'));}));
router.post('/:id/copy',permit('reservations.create'),asyncHandler(async(req,res)=>{const src=await getReservation(req,req.params.id);if(!src)return res.status(404).json({message:'Not found'});const checkIn=new Date(req.body.checkIn||src.checkIn),checkOut=new Date(req.body.checkOut||src.checkOut);const room=req.body.room||null;if(!(checkIn<checkOut))return res.status(400).json({message:'Invalid stay dates'});await ensureAvailable({organization:src.organization,property:src.property,room,checkIn,checkOut});const data=src.toObject();['_id','createdAt','updatedAt','__v'].forEach(k=>delete data[k]);Object.assign(data,{confirmationNumber:`${process.env.BOOKING_PREFIX||'HMS'}-${new Date().getFullYear()}-${uuid().slice(0,8).toUpperCase()}`,checkIn,checkOut,nights:days(checkIn,checkOut),room,status:req.body.status||'confirmed',checkedInAt:undefined,checkedOutAt:undefined,cancelledAt:undefined});const clone=await Reservation.create(data);await roomStatus(req,room,'Reserved',clone.property);await Folio.create({organization:clone.organization,property:clone.property,reservation:clone._id,guest:clone.guest,currency:process.env.DEFAULT_CURRENCY||'INR'});await audit(req,{action:'COPY',module:'reservations',entityType:'Reservation',entityId:clone._id,newValue:clone});res.status(201).json(await clone.populate('guest room roomType'));}));
router.post('/:id/reinstate',permit('reservations.update'),asyncHandler(async(req,res)=>{const r=await getReservation(req,req.params.id);if(!r)return res.status(404).json({message:'Not found'});if(!['cancelled','no-show'].includes(r.status))return res.status(409).json({message:'Only cancelled/no-show reservations can be reinstated'});await ensureAvailable({organization:r.organization,property:r.property,room:r.room,checkIn:r.checkIn,checkOut:r.checkOut,exclude:r._id});r.status=req.body.status||'confirmed';r.cancelledAt=undefined;r.cancellationReason=undefined;await r.save();await roomStatus(req,r.room,'Reserved',r.property);await audit(req,{action:'REINSTATE',module:'reservations',entityType:'Reservation',entityId:r._id,newValue:r});res.json(r)}));
router.post('/:id/split',permit('reservations.update'),asyncHandler(async(req,res)=>{const src=await getReservation(req,req.params.id);if(!src)return res.status(404).json({message:'Not found'});const splitDate=new Date(req.body.splitDate);if(!(new Date(src.checkIn)<splitDate&&splitDate<new Date(src.checkOut)))return res.status(400).json({message:'Split date must be inside stay'});const newRoom=req.body.room||null;await ensureAvailable({organization:src.organization,property:src.property,room:newRoom,checkIn:splitDate,checkOut:src.checkOut,exclude:src._id});const oldOut=src.checkOut;src.checkOut=splitDate;src.nights=days(src.checkIn,splitDate);await src.save();const data=src.toObject();['_id','createdAt','updatedAt','__v'].forEach(k=>delete data[k]);Object.assign(data,{confirmationNumber:`${process.env.BOOKING_PREFIX||'HMS'}-${new Date().getFullYear()}-${uuid().slice(0,8).toUpperCase()}`,checkIn:splitDate,checkOut:oldOut,nights:days(splitDate,oldOut),room:newRoom,status:'confirmed'});const child=await Reservation.create(data);await roomStatus(req,newRoom,'Reserved',child.property);await Folio.create({organization:child.organization,property:child.property,reservation:child._id,guest:child.guest,currency:process.env.DEFAULT_CURRENCY||'INR'});await audit(req,{action:'SPLIT_RESERVATION',module:'reservations',entityType:'Reservation',entityId:src._id,newValue:{child:child._id,splitDate}});res.status(201).json({original:src,split:child});}));
router.post('/:id/merge',permit('reservations.update'),asyncHandler(async(req,res)=>{const a=await getReservation(req,req.params.id),b=await getReservation(req,req.body.withReservationId);if(!a||!b)return res.status(404).json({message:'Reservation not found'});if(String(a.property)!==String(b.property))return res.status(409).json({message:'Merge requires same property'});if(String(a.guest)!==String(b.guest))return res.status(409).json({message:'Merge requires same guest'});const start=new Date(Math.min(+new Date(a.checkIn),+new Date(b.checkIn))),end=new Date(Math.max(+new Date(a.checkOut),+new Date(b.checkOut)));const clash=await Reservation.findOne({organization:a.organization,property:a.property,_id:{$nin:[a._id,b._id]},room:a.room,...overlap(start,end)});if(clash)return res.status(409).json({message:'Merged stay conflicts with another reservation'});a.checkIn=start;a.checkOut=end;a.nights=days(start,end);a.internalNotes=[a.internalNotes,b.internalNotes].filter(Boolean).join('\n');await a.save();await roomStatus(req,b.room,'Vacant Clean',b.property);b.status='cancelled';b.cancellationReason=`Merged into ${a.confirmationNumber}`;b.cancelledAt=new Date();await b.save();await audit(req,{action:'MERGE_RESERVATION',module:'reservations',entityType:'Reservation',entityId:a._id,newValue:{merged:b._id}});res.json({reservation:a,merged:b._id});}));
router.post('/:id/pre-arrival',permit('reservations.update'),asyncHandler(async(req,res)=>{const r=await getReservation(req,req.params.id,'guest');if(!r)return res.status(404).json({message:'Not found'});Object.assign(r.guest,req.body.guest||{});await r.guest.save();r.accompanyingGuests=req.body.accompanyingGuests||r.accompanyingGuests;r.preArrival={completed:true,completedAt:new Date(),signatureName:req.body.signatureName,signatureData:req.body.signatureData,registrationAccepted:!!req.body.registrationAccepted};r.identityVerified=!!req.body.identityVerified;await r.save();await audit(req,{action:'PRE_ARRIVAL',module:'frontdesk',entityType:'Reservation',entityId:r._id,newValue:r.preArrival});res.json(r);}));
router.post('/:id/cancel',permit('reservations.update'),asyncHandler(async(req,res)=>{const r=await getReservation(req,req.params.id);if(!r)return res.status(404).json({message:'Not found'});r.status='cancelled';r.cancelledAt=new Date();r.cancellationReason=req.body.reason;await r.save();await roomStatus(req,r.room,'Vacant Clean',r.property);await audit(req,{action:'CANCEL',module:'reservations',entityType:'Reservation',entityId:r._id,reason:req.body.reason});res.json(r)}));
router.post('/:id/no-show',permit('reservations.update'),asyncHandler(async(req,res)=>{const r=await getReservation(req,req.params.id);if(!r)return res.status(404).json({message:'Not found'});r.status='no-show';await r.save();await roomStatus(req,r.room,'Vacant Clean',r.property);await audit(req,{action:'NO_SHOW',module:'reservations',entityType:'Reservation',entityId:r._id});res.json(r)}));
router.post('/:id/check-in',permit('reservations.update'),asyncHandler(async(req,res)=>{const r=await getReservation(req,req.params.id,'roomType guest');if(!r)return res.status(404).json({message:'Not found'});if(!r.room)return res.status(400).json({message:'Assign a room before check-in'});if(['cancelled','no-show','checked-out'].includes(r.status))return res.status(409).json({message:`Cannot check in reservation with status ${r.status}`});if(req.body.guest)Object.assign(r.guest,req.body.guest);await r.guest.save();if(req.body.accompanyingGuests)r.accompanyingGuests=req.body.accompanyingGuests;r.depositMethod=req.body.depositMethod||r.depositMethod;r.preAuthorizationReference=req.body.preAuthorizationReference||r.preAuthorizationReference;r.identityVerified=req.body.identityVerified!==undefined?!!req.body.identityVerified:r.identityVerified;if(req.body.signatureName)r.preArrival={completed:true,completedAt:new Date(),signatureName:req.body.signatureName,signatureData:req.body.signatureData,registrationAccepted:!!req.body.registrationAccepted};r.status='in-house';r.checkedInAt=new Date();r.digitalKey={keyCode:`KEY-${uuid().slice(0,6).toUpperCase()}`,status:'active',activatedAt:new Date(),expiresAt:r.checkOut};await r.save();await roomStatus(req,r.room,'Occupied Clean',r.property);const folio=await Folio.findOne({organization:r.organization,property:r.property,reservation:r._id});if(folio&&!folio.items.some(x=>x.type==='room')){const roomCharge=(r.rate||r.roomType?.baseRate||0)*r.nights;const tax=roomCharge*((r.taxPercent||0)/100);folio.items.push({type:'room',department:'Rooms',description:`Room charge ${r.nights} night(s)`,qty:r.nights,unitPrice:r.rate||r.roomType?.baseRate||0,amount:roomCharge,tax});if(Number(req.body.depositAmount)>0)folio.payments.push({method:req.body.depositMethod||'Deposit',amount:Number(req.body.depositAmount),reference:req.body.depositReference||'',status:'captured'});await folio.save()}await audit(req,{action:'CHECK_IN',module:'frontdesk',entityType:'Reservation',entityId:r._id,newValue:r});res.json({reservation:r,digitalKey:r.digitalKey,digitalKeyMode:'internal-adapter'});}));
router.post('/:id/digital-key/refresh',permit('reservations.update'),asyncHandler(async(req,res)=>{const r=await getReservation(req,req.params.id);if(!r)return res.status(404).json({message:'Not found'});if(r.status!=='in-house')return res.status(409).json({message:'Digital key requires in-house reservation'});r.digitalKey={keyCode:`KEY-${uuid().slice(0,6).toUpperCase()}`,status:'active',activatedAt:new Date(),expiresAt:r.checkOut};await r.save();await audit(req,{action:'DIGITAL_KEY_REFRESH',module:'frontdesk',entityType:'Reservation',entityId:r._id});res.json({...r.digitalKey.toObject?.()||r.digitalKey,mode:'internal-adapter'});}));
router.post('/:id/check-out',permit('reservations.update'),asyncHandler(async(req,res)=>{const r=await getReservation(req,req.params.id);if(!r)return res.status(404).json({message:'Not found'});const folio=await Folio.findOne({organization:r.organization,property:r.property,reservation:r._id});if(!folio)return res.status(400).json({message:'Folio missing'});const total=folio.items.reduce((s,i)=>s+(i.amount||0)+(i.tax||0)-(i.discount||0),0),paid=folio.payments.reduce((s,p)=>s+(p.amount||0)-(p.refundedAmount||0),0);if(total-paid>0.01&&!req.body.allowOutstanding)return res.status(409).json({message:'Outstanding balance remains',balance:total-paid});r.status='checked-out';r.checkedOutAt=new Date();r.digitalKey.status='expired';r.digitalKey.expiresAt=new Date();await r.save();folio.status='closed';folio.invoiceNumber=folio.invoiceNumber||`INV-${Date.now().toString().slice(-8)}`;folio.invoiceEmail=req.body.invoiceEmail||folio.invoiceEmail;await folio.save();await roomStatus(req,r.room,'Vacant Dirty',r.property);await HousekeepingTask.create({organization:r.organization,property:r.property,room:r.room,reservation:r._id,status:'Dirty',priority:'normal',checklist:[{label:'Replace linen',done:false},{label:'Clean bathroom',done:false},{label:'Replenish amenities',done:false},{label:'Check minibar',done:false},{label:'Vacuum / mop',done:false},{label:'Supervisor inspection',done:false}]});await audit(req,{action:'CHECK_OUT',module:'frontdesk',entityType:'Reservation',entityId:r._id,newValue:r});res.json({reservation:r,folio});}));
module.exports=router;
