const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const {Schema} = mongoose;

const scope = {
  organization: {type: Schema.Types.ObjectId, ref:'Organization', index:true},
  property: {type: Schema.Types.ObjectId, ref:'Property', index:true}
};
const opts = {timestamps:true, toJSON:{virtuals:true}, toObject:{virtuals:true}};

const organizationSchema = new Schema({name:{type:String,required:true}, code:{type:String,unique:true}, status:{type:String,default:'active'}, plan:{type:String,default:'premium'}, defaultCurrency:{type:String,default:'INR'}, timezone:{type:String,default:'Asia/Kolkata'}},opts);
const brandSchema = new Schema({...scope,name:{type:String,required:true},code:String,description:String},opts);
const regionSchema = new Schema({...scope,brand:{type:Schema.Types.ObjectId,ref:'Brand'},name:{type:String,required:true},code:String},opts);
const propertySchema = new Schema({organization:{type:Schema.Types.ObjectId,ref:'Organization',index:true},brand:{type:Schema.Types.ObjectId,ref:'Brand'},region:{type:Schema.Types.ObjectId,ref:'Region'},name:{type:String,required:true},code:{type:String,required:true},type:{type:String,default:'Hotel'},email:String,phone:String,address:String,city:String,state:String,country:{type:String,default:'India'},currency:{type:String,default:'INR'},timezone:{type:String,default:'Asia/Kolkata'},taxId:String,checkInTime:{type:String,default:'14:00'},checkOutTime:{type:String,default:'11:00'},status:{type:String,default:'active'}},opts);
const buildingSchema = new Schema({...scope,name:{type:String,required:true},code:String},opts);
const floorSchema = new Schema({...scope,building:{type:Schema.Types.ObjectId,ref:'Building'},name:{type:String,required:true},number:Number},opts);

const userSchema = new Schema({organization:{type:Schema.Types.ObjectId,ref:'Organization',index:true},properties:[{type:Schema.Types.ObjectId,ref:'Property'}],name:{type:String,required:true},email:{type:String,required:true,unique:true,lowercase:true},password:{type:String,required:true,select:false},role:{type:String,required:true,default:'front_desk'},permissions:[String],department:String,status:{type:String,default:'active'},lastLogin:Date,mfaEnabled:{type:Boolean,default:false}},opts);
userSchema.pre('save', async function(next){if(!this.isModified('password')) return next(); this.password=await bcrypt.hash(this.password,12); next();});
userSchema.methods.comparePassword=function(v){return bcrypt.compare(v,this.password)};

const roomTypeSchema = new Schema({...scope,name:{type:String,required:true},code:String,description:String,baseRate:{type:Number,default:0},defaultOccupancy:{type:Number,default:2},maxOccupancy:{type:Number,default:2},maxAdults:{type:Number,default:2},maxChildren:{type:Number,default:1},extraBedCapacity:{type:Number,default:0},amenities:[String],images:[String],active:{type:Boolean,default:true}},opts);
const roomSchema = new Schema({...scope,building:{type:Schema.Types.ObjectId,ref:'Building'},floor:{type:Schema.Types.ObjectId,ref:'Floor'},roomType:{type:Schema.Types.ObjectId,ref:'RoomType',required:true},number:{type:String,required:true},bedType:String,capacity:Number,extraBedCapacity:Number,smoking:{type:Boolean,default:false},view:String,balcony:Boolean,accessible:Boolean,amenities:[String],images:[String],notes:String,status:{type:String,enum:['Vacant Clean','Vacant Dirty','Occupied Clean','Occupied Dirty','Inspected','Out of Order','Out of Service','Maintenance','Blocked','Reserved'],default:'Vacant Clean'},statusReason:String},opts);
roomSchema.index({property:1,number:1},{unique:true});

const guestSchema = new Schema({...scope,firstName:String,lastName:String,fullName:{type:String,required:true},email:String,phone:String,nationality:String,dateOfBirth:Date,gender:String,idType:String,idNumber:String,idDocumentUrl:String,passportExpiry:Date,visaNumber:String,visaExpiry:Date,address:String,company:String,loyaltyNumber:String,tags:[String],preferences:{room:String,bed:String,floor:String,food:String,other:[String]},allergies:[String],notes:String,consents:{marketing:Boolean,whatsapp:Boolean,email:Boolean},stats:{totalStays:{type:Number,default:0},totalNights:{type:Number,default:0},lifetimeSpend:{type:Number,default:0},averageRate:{type:Number,default:0}}},opts);

const reservationSchema = new Schema({...scope,confirmationNumber:{type:String,required:true,index:true},guest:{type:Schema.Types.ObjectId,ref:'Guest',required:true},accompanyingGuests:[{name:String,age:Number,nationality:String,idType:String,idNumber:String}],roomType:{type:Schema.Types.ObjectId,ref:'RoomType',required:true},room:{type:Schema.Types.ObjectId,ref:'Room'},checkIn:{type:Date,required:true},checkOut:{type:Date,required:true},nights:Number,adults:{type:Number,default:1},children:{type:Number,default:0},ratePlan:String,mealPlan:String,source:{type:String,default:'Direct'},reservationType:{type:String,default:'confirmed'},status:{type:String,enum:['confirmed','tentative','waitlist','guaranteed','non-guaranteed','walk-in','group','corporate','travel-agent','complimentary','house-use','day-use','long-stay','in-house','checked-out','cancelled','no-show'],default:'confirmed'},eta:String,specialRequests:[String],internalNotes:String,guestNotes:String,alerts:[String],rate:{type:Number,default:0},taxPercent:{type:Number,default:12},depositRequired:{type:Number,default:0},depositPaid:{type:Number,default:0},groupId:String,corporateAccount:{type:Schema.Types.ObjectId,ref:'CorporateAccount'},travelAgent:{type:Schema.Types.ObjectId,ref:'TravelAgent'},preArrival:{completed:{type:Boolean,default:false},completedAt:Date,signatureName:String,signatureData:String,registrationAccepted:{type:Boolean,default:false}},identityVerified:{type:Boolean,default:false},depositMethod:String,preAuthorizationReference:String,digitalKey:{keyCode:String,status:{type:String,default:'inactive'},activatedAt:Date,expiresAt:Date},checkedInAt:Date,checkedOutAt:Date,cancelledAt:Date,cancellationReason:String},opts);
reservationSchema.index({property:1,checkIn:1,checkOut:1});

const folioItemSchema = new Schema({type:String,department:String,description:String,qty:{type:Number,default:1},unitPrice:{type:Number,default:0},amount:{type:Number,default:0},tax:{type:Number,default:0},discount:{type:Number,default:0},sourceRef:String,postedAt:{type:Date,default:Date.now}},{_id:true});
const paymentSchema = new Schema({method:String,kind:{type:String,default:'settlement'},amount:Number,currency:{type:String,default:'INR'},reference:String,status:{type:String,default:'captured'},paidAt:{type:Date,default:Date.now},refundedAmount:{type:Number,default:0}},{_id:true});
const folioSchema = new Schema({...scope,reservation:{type:Schema.Types.ObjectId,ref:'Reservation',required:true,unique:true},guest:{type:Schema.Types.ObjectId,ref:'Guest'},items:[folioItemSchema],payments:[paymentSchema],subFolios:[{name:String,itemIds:[Schema.Types.ObjectId],payerType:{type:String,default:'guest'},payerName:String,status:{type:String,default:'open'}}],routingRules:[{department:String,target:String}],status:{type:String,default:'open'},invoiceNumber:String,invoiceEmail:String,creditNotes:[{amount:Number,reason:String,date:Date}],currency:{type:String,default:'INR'}},opts);
folioSchema.virtual('totalCharges').get(function(){return this.items.reduce((s,i)=>s+(i.amount||0)+(i.tax||0)-(i.discount||0),0)});
folioSchema.virtual('totalPaid').get(function(){return this.payments.reduce((s,p)=>s+(p.amount||0)-(p.refundedAmount||0),0)});
folioSchema.virtual('balance').get(function(){return this.totalCharges-this.totalPaid});

const hkSchema = new Schema({...scope,room:{type:Schema.Types.ObjectId,ref:'Room',required:true},reservation:{type:Schema.Types.ObjectId,ref:'Reservation'},assignedTo:{type:Schema.Types.ObjectId,ref:'User'},priority:{type:String,default:'normal'},status:{type:String,enum:['Dirty','Assigned','Cleaning','Clean','Inspected','DND','Turndown Required','Maintenance Required'],default:'Dirty'},checklist:[{label:String,done:Boolean}],startedAt:Date,completedAt:Date,inspectedAt:Date,supervisor:{type:Schema.Types.ObjectId,ref:'User'},minibar:[{item:String,qty:Number,amount:Number}],damages:[{description:String,amount:Number,photo:String}],notes:String},opts);

const approvalSchema = new Schema({...scope,type:String,referenceType:String,referenceId:Schema.Types.ObjectId,requestedBy:{type:Schema.Types.ObjectId,ref:'User'},assignedTo:{type:Schema.Types.ObjectId,ref:'User'},amount:Number,reason:String,status:{type:String,enum:['pending','approved','rejected','cancelled'],default:'pending'},decisionReason:String,decidedBy:{type:Schema.Types.ObjectId,ref:'User'},decidedAt:Date},opts);
const auditSchema = new Schema({...scope,user:{type:Schema.Types.ObjectId,ref:'User'},action:String,module:String,entityType:String,entityId:String,oldValue:Schema.Types.Mixed,newValue:Schema.Types.Mixed,reason:String,ip:String,userAgent:String},{timestamps:true});
const notificationSchema = new Schema({...scope,recipientType:String,recipient:String,channel:{type:String,enum:['in-app','email','sms','whatsapp','push'],default:'in-app'},template:String,event:String,payload:Schema.Types.Mixed,status:{type:String,default:'queued'},sentAt:Date,error:String},opts);

module.exports = {
 Organization: mongoose.model('Organization',organizationSchema), Brand:mongoose.model('Brand',brandSchema), Region:mongoose.model('Region',regionSchema), Property:mongoose.model('Property',propertySchema), Building:mongoose.model('Building',buildingSchema), Floor:mongoose.model('Floor',floorSchema), User:mongoose.model('User',userSchema), RoomType:mongoose.model('RoomType',roomTypeSchema), Room:mongoose.model('Room',roomSchema), Guest:mongoose.model('Guest',guestSchema), Reservation:mongoose.model('Reservation',reservationSchema), Folio:mongoose.model('Folio',folioSchema), HousekeepingTask:mongoose.model('HousekeepingTask',hkSchema), ApprovalRequest:mongoose.model('ApprovalRequest',approvalSchema), AuditLog:mongoose.model('AuditLog',auditSchema), Notification:mongoose.model('Notification',notificationSchema)
};
