const fs=require('fs');const path=require('path');const cp=require('child_process');
const root=path.resolve(__dirname,'..');
let failures=[];let passes=[];
function pass(x){passes.push(x);console.log('PASS',x)}function fail(x){failures.push(x);console.error('FAIL',x)}
function walk(dir,ext){let out=[];for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())out=out.concat(walk(p,ext));else if(p.endsWith(ext))out.push(p)}return out}
for(const f of walk(path.join(root,'server'),'.js')){try{cp.execFileSync(process.execPath,['--check',f],{stdio:'pipe'});pass('syntax '+path.relative(root,f))}catch(e){fail('syntax '+path.relative(root,f))}}
const app=fs.readFileSync(path.join(root,'server/app.js'),'utf8');for(const route of ['/api/health','/api/auth','/api/dashboard','/api/rooms','/api/reservations','/api/folios','/api/housekeeping','/api/modules','/api/reports','/api/approvals','/api/audit','/api/admin','/api/ai','/api/pos','/api/night-audit','/api/notifications','/api/commercial','/api/procurement','/api/operations','/api/public/payments'])app.includes(route)?pass('route '+route):fail('route '+route);
const defs=require(path.join(root,'server/config/enterpriseModules'));const required=['rate-plans','rate-rules','crs-allotments','channel-mappings','groups','loyalty-accounts','service-requests','laundry-orders','linen-items','minibar-entries','pos-orders','kitchen-tickets','spa-appointments','events','conference-rooms','inventory-items','purchase-orders','suppliers','ar-accounts','ap-accounts','cashier-shifts','corporate-accounts','travel-agents','transport-requests','maintenance-work-orders','preventive-maintenance','assets','lost-found','incidents','employees','shifts','attendance','documents','forecasts','currencies','translations','tax-rules','integrations','webhooks','door-lock-keys','iot-devices','energy-readings','subscriptions','plans','feature-flags','backup-runs','integration-logs','promo-codes','hotel-packages'];for(const m of required)defs[m]?pass('module '+m):fail('module '+m);
const imports=[];for(const f of walk(path.join(root,'client/src'),'.jsx')){const txt=fs.readFileSync(f,'utf8');for(const m of txt.matchAll(/from\s*['"](\.\.?\/[^'"]+)['"]/g))imports.push([f,m[1]])}for(const[f,rel]of imports){const base=path.resolve(path.dirname(f),rel);const ok=['','.js','.jsx'].some(x=>fs.existsSync(base+x))||fs.existsSync(path.join(base,'index.jsx'))||fs.existsSync(path.join(base,'index.js'));ok?pass('client import '+path.relative(root,f)+' -> '+rel):fail('client import '+path.relative(root,f)+' -> '+rel)}

const procurement=fs.readFileSync(path.join(root,'server/routes/procurement.js'),'utf8');procurement.includes('qtyOnHand')?pass('procurement GRN updates qtyOnHand'):fail('procurement GRN qtyOnHand');
const reservations=fs.readFileSync(path.join(root,'server/routes/reservations.js'),'utf8');reservations.includes("permit('reservations.update')")?pass('reservation mutation RBAC'):fail('reservation mutation RBAC');reservations.includes('findById(req.params.id)')?fail('reservation unscoped findById'):pass('reservation tenant-safe id lookups');
const operations=fs.readFileSync(path.join(root,'server/routes/operations.js'),'utf8');for(const marker of ['/laundry/:id/status','/spa/:id/status','/maintenance/:id/status','/forecast/generate','/inventory/:id/adjust'])operations.includes(marker)?pass('workflow '+marker):fail('workflow '+marker);

const rootPkg=require(path.join(root,'package.json'));rootPkg.version==='12.2.0'?pass('root version 12.2.0'):fail('root version 12.2.0');
const clientPkg=require(path.join(root,'client/package.json'));clientPkg.version==='12.2.0'?pass('client version 12.2.0'):fail('client version 12.2.0');
const serverPkg=require(path.join(root,'server/package.json'));serverPkg.version==='12.2.0'?pass('server version 12.2.0'):fail('server version 12.2.0');
const layout=fs.readFileSync(path.join(root,'client/src/Layout.jsx'),'utf8');layout.includes('/ops/${x.key}')?pass('dedicated operations routing'):fail('dedicated operations routing');
const opsUi=fs.readFileSync(path.join(root,'client/src/pages/OperationsCenter.jsx'),'utf8');for(const m of ['laundry-orders','minibar-entries','spa-appointments','inventory-items','maintenance-work-orders','transport-requests','lost-found','incidents','cashier-shifts'])opsUi.includes(`'${m}'`)?pass('operations UI '+m):fail('operations UI '+m);


const authRoutes=fs.readFileSync(path.join(root,'server/routes/auth.js'),'utf8');authRoutes.includes('grants:')?pass('auth returns role grants'):fail('auth role grants');
const folios=fs.readFileSync(path.join(root,'server/routes/folios.js'),'utf8');folios.includes("kind=req.body.kind||'settlement'")?pass('folio settlement/advance payment validation'):fail('folio payment validation');
const approvals=fs.readFileSync(path.join(root,'server/routes/approvals.js'),'utf8');approvals.includes("referenceType==='PurchaseRequest'")?pass('approval updates purchase request status'):fail('approval procurement linkage');
const login=fs.readFileSync(path.join(root,'client/src/pages/Login.jsx'),'utf8');login.includes('getHomeForRole')?pass('role-specific login redirect'):fail('role-specific login redirect');
const apiClient=fs.readFileSync(path.join(root,'client/src/api.js'),'utf8');apiClient.includes('__propertyRetry')?pass('stale property context auto-retry'):fail('property context retry');
const approvalUi=fs.readFileSync(path.join(root,'client/src/pages/Approvals.jsx'),'utf8');approvalUi.includes('key={x._id}')?pass('approval row keys'):fail('approval row keys');
const folioUi=fs.readFileSync(path.join(root,'client/src/pages/Folios.jsx'),'utf8');folioUi.includes('Accept payment')&&folioUi.includes('Advance / Deposit')?pass('folio payment UI'):fail('folio payment UI');
const procurementUi=fs.readFileSync(path.join(root,'client/src/pages/Procurement.jsx'),'utf8');procurementUi.includes("can.rfq(selectedStatus)")&&procurementUi.includes('supplierQuotes')?pass('procurement stage-gated UI'):fail('procurement stage gating');
const procurementFix=fs.readFileSync(path.join(root,'server/routes/procurement.js'),'utf8');!procurementFix.includes('totaldoc')&&procurementFix.includes("selectedQuoteAmount=chosen.total;doc.status='Quote Selected'")?pass('procurement compare runtime fix'):fail('procurement compare runtime fix');
const posFix=fs.readFileSync(path.join(root,'server/routes/pos.js'),'utf8');posFix.includes('req.body.reservationId||order.reservationId')?pass('POS room charge selected reservation fix'):fail('POS room charge selected reservation fix');
const errorFix=fs.readFileSync(path.join(root,'server/middleware/errors.js'),'utf8');errorFix.includes("err?.name==='CastError'")?pass('controlled invalid ObjectId errors'):fail('controlled invalid ObjectId errors');
const payFix=fs.readFileSync(path.join(root,'server/routes/payments.js'),'utf8');payFix.includes('idempotent:true')?pass('payment capture idempotency'):fail('payment capture idempotency');
console.log(`\n${passes.length} passed, ${failures.length} failed`);process.exit(failures.length?1:0);
